#!/bin/bash
if [ ! -f $1 ]; then
  echo "File not exists $1"
  exit 1
fi
objname=`echo $1 | awk -F "/" '{print $NF}' | awk -F "." '{print $1}'`
base=/mnt
aufsdir=$base/$objname
EXISTS=`df -hP | grep  $aufsdir/`
if [  -n "$EXISTS" ]; then
    echo "Shutting down Docker"
    for pid in `lsof | grep $aufsdir | sed -e's/  / /g' |cut -d' ' -f4`; do kill -9 $pid >/dev/null 2>&1; done
    echo "Stop Proc in Image.  OK"
    RETVAL=$?
    if [ $RETVAL -ne 0 ]; then
        exit $RETVAL
    fi
    sleep 1
    umount $aufsdir/dev/pts
    umount $aufsdir/dev/shm
    umount $aufsdir/dev
    umount $aufsdir/proc
    umount $aufsdir/sys
    umount $aufsdir/tmp
    umount $aufsdir/root
    umount $aufsdir
    echo "Umount Image. Ok"
else
    echo "Not Mounted: $aufsdir"
fi
