#!/bin/sh
# PowerBy xuwl
# 2016.11.25 ver 0.0.1

cfgfile=/etc/docker.lst
srvname=estore-service
base=/mnt
s_mount=`which single-mount`
if [ ! -f $cfgfile ]; then
  echo -e "Docker list configfile: $cfgfile loss. Nothing deal\n"
  exit 1
fi
while read LINE; do
  echo -e "==============Start mount Image:  $LINE==============\n"
  echo n|${s_mount} $LINE
  RETVAL=$?
  if [ $RETVAL -ne 0 ]; then
      echo -e "Mount Image Failed\n"
      continue
      #exit 1
  else
      echo -e "Mount Image OK\n"
  fi
  objname=`echo $LINE | awk -F "/" '{print $NF}' | awk -F "." '{print $1}'`
  aufsdir=$base/$objname
  echo -e "Start Docker::$aufsdir\n"
  chroot $aufsdir service $srvname start
  RETVAL=$?
  if [ $RETVAL -ne 0 ]; then
      echo -e "Start Docker::$aufsdir       Failed\n"
  else
      echo -e "Start Docker::$aufsdir           OK\n"
  fi
  echo -e "================================\n"
#  echo -n " $LINE"
done < $cfgfile
~
